version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/reactapp
permissions:
  - object: /var/www/html/reactapp
    pattern: "**"
    owner: ec2-user
    group: apache
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build_react_app.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_react_app.sh
      timeout: 300
      runas: ec2-user
